version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/versioning/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/seeker/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/identity/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/logging/"
    schedule:
      interval: "daily"
